version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  web:
    build: ../backend
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build:
      context: ../frontend
    volumes:
      - ../frontend:/app
    depends_on:
      - web

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-local.conf:/etc/nginx/conf.d/default.conf
      - static_data:/var/www/static/
      - media_data:/var/www/media/
    depends_on:
      - frontend
      - web

volumes:
  postgres_data:
  static_data:
  media_data: