version: '3.3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: foodgram_db

  backend:
    build:
      context: ../backend
    volumes:
      - ../backend/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: foodgram_db
      DB_USER: foodgram_user
      DB_PASSWORD: secure_password
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    build:
      context: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
