version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=your_db
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
